/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Sharon Kunne (https://sketchfab.com/sharonkunne)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mermaid-potion-2363db11631045dea8f84c8421578002
Title: Mermaid Potion
*/
"use client";

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function Potion(props) {
  const { nodes, materials } = useGLTF("/models/potion-transformed.glb");

  const modelRef = useRef();

  useFrame(() => {
    modelRef.current.rotation.y += 0.01;
  });

  return (
    <group ref={modelRef} {...props} dispose={null} scale={[5, 5, 5]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Potion01_potion01_metal_0.geometry}
        material={materials.potion01_metal}
        position={[0, 0.047, 0.151]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.038}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Potion01_potion01_glass_0.geometry}
        material={materials.potion01_glass}
        position={[0, 0.047, 0.151]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.038}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Potion02_potion02_metal_0.geometry}
        material={materials.potion02_metal}
        position={[0.153, 0.047, 0.151]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.038}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Potion02_potion02_glass_0.geometry}
        material={materials.potion02_glass}
        position={[0.153, 0.047, 0.151]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.038}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Potion03_potion03_glass_0.geometry}
        material={materials.potion03_glass}
        position={[-0.153, 0.047, 0.151]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.038}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Potion03_potion03_metal_0.geometry}
        material={materials.potion03_metal}
        position={[-0.153, 0.047, 0.151]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.038}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Potion04_potion04_glass_0.geometry}
        material={materials.potion04_glass}
        position={[0, 0.142, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.038}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Potion04_potion04_metal_0.geometry}
        material={materials.potion04_metal}
        position={[0, 0.142, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.038}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Potion06_potion06_glass_0.geometry}
        material={materials.potion06_glass}
        position={[0.153, 0.142, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.038}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Potion06_potion06_metal_0.geometry}
        material={materials.potion06_metal}
        position={[0.153, 0.142, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.038}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Potion07_potion07_glass_0.geometry}
        material={materials.potion07_glass}
        position={[-0.153, 0.142, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.038}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Potion07_potion07_metal_0.geometry}
        material={materials.potion07_metal}
        position={[-0.153, 0.142, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.038}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Shelf01_shelf_mt_0.geometry}
        material={materials.shelf_mt}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.038}
      />
    </group>
  );
}

useGLTF.preload("/models/potion-transformed.glb");
